node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/CHERRISHGRY/jktest.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      //mvnHome = tool 'M3'
   }
   stage('Package'){
        dir(BackEnd){
            sh  'mvn clean package -DskipTests'
        }
   }

   stage('Build Image'){
           dir(BackEnd/themis-user){
               docker.build("192.168.1.101:5005/oxchains/themis-user:latest").push()
           }
    }


   stage('Deploy') {
           //替换rpcserver.yaml的镜像版本号，待完成
           dir('BackEnd/themis-user') {
               //scp rpcserver.yaml 到 k8s的master上
               //sh 'sshpass -p oxchains scp themis-user.yaml root@192.168.1.137:~/apps/themis-user.yml'

               //远程登录k8s集群master主机,更新镜像，这里面要进行判断，第一次create
               sh 'sshpass -p oxchains ssh root@192.168.1.137 "kubectl create -f ~/apps/themis-user.yaml"'
           }
       }
}